-- phpMyAdmin SQL Dump
-- version 4.2.7.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 14 Okt 2016 pada 15.50
-- Versi Server: 5.6.20
-- PHP Version: 5.5.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `kemiskinandb`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `program`
--

CREATE TABLE IF NOT EXISTS `program` (
`id` int(11) NOT NULL,
  `program` varchar(400) NOT NULL,
  `kegiatan` varchar(400) NOT NULL,
  `jumlah_pagu` double(15,2) NOT NULL,
  `skpd` varchar(50) NOT NULL,
  `id_klaster` int(11) NOT NULL,
  `keterangan` text NOT NULL,
  `tahun` int(4) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=34 ;

--
-- Dumping data untuk tabel `program`
--

INSERT INTO `program` (`id`, `program`, `kegiatan`, `jumlah_pagu`, `skpd`, `id_klaster`, `keterangan`, `tahun`) VALUES
(1, 'Distribusi Dana Stimulus Rukun Tetangga', 'Distribusi Dana Stimulus Rukun Tetangga', 135600000.00, 'BPM PEMDES', 2, 'Program Distribusi Dana Stimulus Rukun Tetangga di berikan kepada keluarga yang kurang mampu memlalui pemerintah terdekat. pendistribusian dana stimulus rukun tetangga ini diharapkan dapat membantu mensejahterakan kehidupan ekonomi dari setiap keluarga miskin yang berada di Kabupaten Sumbawa Barat.', 2014),
(3, 'Program Rehab Rumah', 'Peningkatan Kualitas Rumah Tidak Layak Huni Bagi Masyarkat Berpenghasil Rendah', 190920000.00, 'BPM PEMDES', 2, 'Program Distribusi Dana Stimulus Rukun Tetangga di berikan kepada keluarga yang kurang mampu memlalui pemerintah terdekat. pendistribusian dana stimulus rukun tetangga ini diharapkan dapat membantu mensejahterakan kehidupan ekonomi dari setiap keluarga miskin yang berada di Kabupaten Sumbawa Barat. ', 2014),
(6, 'Program Pendidikan Anak Usia Dini', 'Pembangunan Gedung Sekolah', 1223100000.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(7, 'Program Pendidikan Menengah', 'Pembangunan Gedung Sekolah', 522000000.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(8, 'Program Peningkatan Mutu Sarana dan Prasarana Sekolah', 'Peningkatan Mutu Sarana dan Prasarana Pendidikan Dasar (Optimalisasi DAK 2012)', 7085951841.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(9, 'Program Peningkatan Mutu Sarana dan Prasarana Sekolah', 'Peningkatan Mutu Sarana dan Prasarana Pendidikan Dasar', 944653400.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(10, 'Program Pendidikan Tinggi', 'Dukungan Pembiayaan Penyelenggaraan  Pendidikan Tinggi', 2300105500.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(11, 'Program Peningkatan Derajat Pendidikan Masyarakat', 'Dukungan Pembiayaan Penyelenggaraan Pendidikan Pra Sekolah, Pendidikan Dasar dan Menengah', 2380800000.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(12, 'Program Pembangunan Sarana Prasarana Pendidikan Dasar', 'Pembangunan dan/atau Pemeliharaan Sekolah Dasar (SD)', 2837200000.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(13, 'Program Pembangunan Sarana Prasarana Pendidikan Dasar', 'Pembangunan dan/atau Pemeliharaan Sekolah SMP/MTs', 1795129000.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(14, 'Program Pembangunan Sarana Prasarana Pendidikan Dasar', 'Pengadaan atau Bantuan Sarana Penunjang Pendidikan Sekolah Dasar (SD)', 1617000000.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(15, 'Program Pembangunan Sarana Prasarana Pendidikan Dasar', 'Pengadaan atau Bantuan Sarana Penunjang Pendidikan dan Pelatihan pada SMP/MTs', 1406000000.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(16, 'Program Pembangunan Sarana Prasarana Pendidikan Menengah', 'Pembangunan dan/atau Pemeliharaan Sekolah SMA/MA', 1460100000.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(17, 'Program Pembangunan Sarana Prasarana Pendidikan Menengah', 'Pembangunan dan/atau Pemeliharaan Sekolah SMK', 1994850000.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(18, 'Program Pembangunan Sarana Prasarana Pendidikan Menengah', 'Pengadaan atau Bantuan Sarana Penunjang Pendidikan dan Pelatihan pada SMK', 697675000.00, 'DIKBUDPORA', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(19, 'Program Upaya Kesehatan Masyarakat', 'Peningkatan Mutu Pelayanan Kesehatan (DAK)', 5121349000.00, 'DIKES', 2, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(20, 'Program Pengembangan dan Pengelolaan Jaringan Irigasi, Rawa dan Jaringan Pengairan Lainnya', 'Pembangunan jaringan air bersih/air minum', 9437982162.00, 'DPU', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(21, 'Program Pengembangan dan Pengelolaan Jaringan Irigasi, Rawa dan Jaringan Pengairan Lainnya', 'Pelaksanaan Program Pengembangan dan Pengelolaan Sistem Irigasi Partisipatif (PPSIP) (NTB ? WISMP II)', 175000000.00, 'DPU', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(22, 'Program Pengembangan dan Pengelolaan Jaringan Irigasi, Rawa dan Jaringan Pengairan Lainnya', 'Pelaksanaan Program Pengembangan dan Pengelolaan Sistem Irigasi Partisipatif (PPSIP) (LOAN ? WISMP II)', 492490000.00, 'DPU', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(23, 'Program Pembangunan Infrastruktur Perdesaaan', 'Pembangunan Sarana dan Prasarana Pedesaaan', 3795750000.00, 'DPU', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(24, 'Program Lingkungan Sehat Pemukiman dan Fasilitas Umum', 'Penyediaan Sarana Sanitasi Pemukiman dan Fasilitas Umum', 3617896000.00, 'DPU', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(25, 'Program Peningkatan Kesejahteraan Petani', 'Pelatihan Petani dan Pelaku Agribisnis', 450399130.00, 'DISHUTBUNTAN', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(26, 'Program Peningkatan Kesejahteraan Petani', 'Penguatan Kelembagaan Petani (WISMP)', 236611000.00, 'DISHUTBUNTAN', 4, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(27, 'Program Peningkatan Ketahanan Pangan Pertanian / Perkebunan', 'Pengembangan Cadangan Pangan Daerah', 3330440000.00, 'DISHUTBUNTAN', 3, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(28, 'Program rehabilitasi hutan dan lahan', 'Pengadaan Bibit Untuk Pemanfaatan Lahan Kering/Tidur dan Pengembangan MDM (Model Das Mikro)', 178600000.00, 'DISHUTBUNTAN', 3, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(29, 'Program Peningkatan Penerapan Teknologi Pertanian / Perkebunan', 'Pengadaan sarana dan prasarana teknologi pertanian tepat guna', 1291879100.00, 'DISHUTBUNTAN', 5, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(30, 'Program Pemberdayaan Fakir Miskin, Komunitas Adat Terpencil (KAT) dan Penyandang Masalah Kesejahteraan Sosial (PMKS) Lainnya', 'Pemberdayaan Sosial Bagi Sasaran Program Keluarga Harapan', 69222500.00, 'DISOSNAKERTRANS', 3, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(31, 'Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja', 'Pendidikan dan Pelatihan Ketrampilan Bagi Pencari Kerja', 33276000.00, 'DISOSNAKERTRANS', 4, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(32, 'Program Pengembangan Kewirausahaan dan Keunggulan Kompetitif Usaha Kecil Menengah', 'Penyelenggaraan Pelatihan Kewirausahaan', 2727164500.00, 'DISPERINDAGKOP & UMKM', 4, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014),
(33, 'Program Pengembangan Industri Kecil dan Menengah', 'Pembinaan Industri Kecil dan Menengah dalam Memperkuat Jaringan Klaster Industri', 1311053985.00, 'DISPERINDAGKOP & UMKM', 4, 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2014);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `program`
--
ALTER TABLE `program`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `program`
--
ALTER TABLE `program`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=34;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
